RouteC41G2PL/Models/ErrorViewModel.cs
using System;

namespace RouteC41G2PL.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RouteC41G2PL/ViewModels/ErrorViewModel.cs
using System;

namespace RouteC41G2PL.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RouteC41G2PL/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Route.C41.G02.BLL.interfaces;
using RouteC41G2DAL.Models;
using System;

namespace RouteC41G2PL.Controllers
{
    public class DepartmentController : Controller
    {
        // inhertiance : Departmentcontroller is a controller

        //composition : Departmentcontroller has a DepartmentController

        private readonly IDepartmentRepository _departmentsRepo;
        private readonly IHostEnvironment _env;

        public DepartmentController(IDepartmentRepository departmentRepo, IHostEnvironment env)
        {
            _departmentsRepo = departmentRepo;/*new DepartmentRepository(new AppDbContext);*/
            _env = env;
        }


        

        // / Department / Index 
        [HttpGet]
        public IActionResult Index()
        {
            TempData.Keep();

            ViewData["Message"] = "HELLO VIEWDATA";

            ViewBag.Message= "HELLO VIEWBAG";

            var departments = _departmentsRepo.GetAll();
            return View(departments);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid) // Server side Validation
            {
                var count = _departmentsRepo.Add(department);
                if (count > 0)
                {
                    TempData["message"] = "successfully";

                }
                else
                {
                    TempData["message"] = "not created:(";

                }
                    return RedirectToAction(nameof(Index));
                
            }
            return View(department);
        }

        [HttpGet]
        public IActionResult Details(int? id, string ViewName = "Details")
        {
            if (!id.HasValue)

                return BadRequest();
            var department = _departmentsRepo.Get(id.Value);

            if (department == null)
                return NotFound();
            return View(ViewName, department);


        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {

            return Details(id, "Edit");



            ///if (!id.HasValue)

            //    return BadRequest();

            //var department = _departmentsRepo.Get(id.Value);

            //if (department == null)
            //    return NotFound();

            //return View(department);






        }

        [HttpPost]
        public IActionResult Edit([FromRoute] int id, Department department)
        {
            if (id != department.Id)
                return BadRequest();
            if (!ModelState.IsValid)
            {
                return View(department);
            }
            try
            {
                _departmentsRepo.Update(department);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                if (_env.IsDevelopment())
                {
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
                else
                    ModelState.AddModelError(string.Empty, "An Error Has Occurred during Updating Department");

                return View(department);

            }

        }


        public IActionResult Delete(int? id)
        {
            return Details(id, "Delete");
        }
        [HttpPost]
        public IActionResult Delete(Department department)
        {
            try
            {
                _departmentsRepo.Delete(department);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                if (_env.IsDevelopment())
                {
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
                else
                    ModelState.AddModelError(string.Empty, "An Error Has Occurred during Deleting Department");

                return View(department);
            }





        }
    }
}

RouteC41G2PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RouteC41G2PL.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RouteC41G2PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RouteC41G2PL/Views/Department/Create.cshtml
@model Department
@{
    ViewData["Title"] = "Create";
}

<h1>Create New Department</h1>
<br />
<br />


<form asp-action="Create">
    
    


    <partial name="PartialViews/CreateEditDepartmentPartial" />



    <input type="submit" value="Create" class="btn btn-primary" />
    <a asp-action="Index" class="btn btn-light">Back To List></a>


</form>

RouteC41G2PL/Views/Department/Delete.cshtml
@model Department

@{
    ViewData["Title"] = "Delete";
}

<h1> Are You Sure To Delete Department </h1>

<form asp-action="Delete">


    <partial name="PartialViews/DetailsDeleteDepartmentPartial" />

    <input type="submit" value="Delete" class="btn btn-danger" />
    <a asp-action="Index" class="btn btn-light">Cancel</a>

</form>

RouteC41G2PL/Views/Department/Details.cshtml
@model Department
@{
    ViewData["Title"] = "Department Details";
}

<h1> Department Details</h1>
<br />
<br />


<div>

    <partial name="PartialViews/DetailsDeleteDepartmentPartial" />

   

    <a  asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>

    <a  asp-action="Index" class="btn btn-light">Back To List</a>








    








</div>

RouteC41G2PL/Views/Department/Edit.cshtml
@model Department
@{
    ViewData["Title"] = "Edit Department";
}

<h1>Edit Department</h1>

<form asp-action="Edit" asp-controller="Department" method="post">

    <partial name="PartialViews/CreateEditDepartmentPartial" />


    <input type="submit" value="save" class="btn btn-primary" />
    <a asp-action="Index" class="btn btn-light">Cancel</a>



</form>

RouteC41G2PL/Views/Department/Index.cshtml
@model IEnumerable<Department>
@{
    ViewData["Title"] = "Index";
    string viewDataMessage = ViewData["Message"] as string;
    string vbagmessage = ViewBag.Message;

}

@if (!String.IsNullOrEmpty(TempData["message"] as string))
{
    <div class=" alert alert-danger">
        @TempData["Message"]
    </div>

}


@* <div class="alert alert-warning" >
    @ViewData["Message"]
</div>

<div class="alert alert-success">
    @ViewBag.Message
</div>
 *@






<h1>Index</h1>

<h1>All Department</h1>
<a a asp-controller="Department" asp-action="create" class="btn btn -primary">create new department</a>
<br />

@if (Model.Count() > 0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th> @Html.DisplayNameFor(D => D.Code) </th>
                <th>@Html.DisplayNameFor(D => D.Name)</th>
                <th>@Html.DisplayNameFor(D => D.DateOfCreation)</th>
                
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var department in Model)
            {
                <tr>
                    <td>@department.Code</td>
                    <td>@department.Name</td>
                    <td>@department.DateOfCreation</td>

                    <partial name="_ButtonsPartial" model="department.Id" />

                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="mt-4 alert alert-warning">
        <h3>There is NO Department:(</h3>

    </div>
}

RouteC41G2PL/Views/Department/PartialViews/CreateEditDepartmentPartial.cshtml
@model Department
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="form-group">
    <label class="col-from-label" asp-for="Code"></label>
    <input asp-for="Code" class="form-control" />
    <span asp-validation-for="Code" class="text-danger"></span>
</div>
<div class="form-group">
    <label class="col-from-label" asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="form-group">
    <label class="col-from-label" asp-for="DateOfCreation"></label>
    <input asp-for="DateOfCreation" class="form-control" />
    <span asp-validation-for="DateOfCreation" class="text-danger"></span>
</div>

RouteC41G2PL/Views/Department/PartialViews/DetailsDeleteDepartmentPartial.cshtml
@model Department


<div class="form-group">
    <label class="col-form-label" asp-for="Code"></label>
    <input asp-for="Code" class="form-control" readonly />

</div>
<div class="form-group">
    <label class="col-form-label" asp-for="Name"></label>
    <input asp-for="Name" class="form-control" readonly />
</div>
<div class="form-group">
    <label class="col-form-label" asp-for="DateOfCreation"></label>
    <input asp-for="DateOfCreation" class="form-control" readonly />

</div>

RouteC41G2PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RouteC41G2PL/Views/Shared/_ButtonsPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i>  Details
    </a>
</td>
<td>
	<a  asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i>  Update
    </a>
</td>
<td>
    <a  asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i>  Delete
    </a>
</td>

RouteC41G2PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RouteC41G2PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RouteC41G2PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RouteC41G2PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>